--A)O nome de todos os produtos e quantas vezes ele foi vendido, mesmo que não
--tenha sido vendido ainda;

SELECT PRODUCT.NMPRODUCT, ISNULL(COUNT(PRODUCTREQUEST.CDPRODUCT),0) AS TIMESORDERED
FROM PRODUCT INNER JOIN PRODUCTREQUEST
ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY PRODUCT.NMPRODUCT;

--B)O nome do fornecedor, e o número de produtos que ele fornece, mesmo que
--não tenha fornecido produto algum;

SELECT SUPPLIER.NMSUPPLIER, ISNULL(COUNT(PRODUCT.CDSUPPLIER),0) AS PRODUCTSSUPPLIED
FROM SUPPLIER INNER JOIN PRODUCT
ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER 
GROUP BY SUPPLIER.NMSUPPLIER;

--C)O nome do fornecedor, o produto e qual o total de produtos dele já vendidos.
--Uma linha do total por fornecedor e uma linha com o total geral;

SELECT SUPPLIER.NMSUPPLIER, PRODUCT.NMPRODUCT, SUM(PRODUCTREQUEST.QTAMOUNT) AS TOTALSOLD
FROM SUPPLIER INNER JOIN PRODUCT
ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER
INNER JOIN PRODUCTREQUEST
ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT GROUP BY ROLLUP(SUPPLIER.NMSUPPLIER, PRODUCT.NMPRODUCT);

------------------------

--D) O nome do cliente, o produto e o total que o cliente já gastou com esse
--produto. Uma linha com o total por cliente e uma linha com o total geral;SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, SUM(PRODUCTREQUEST.QTAMOUNT * PRODUCTREQUEST.VLUNITARY) AS TOTALSPENTFROM CUSTOMER INNER JOIN REQUEST ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMERINNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUESTINNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCTGROUP BY ROLLUP(CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT);---------------------------E)O nome e o telefone de todos os clientes que ainda não compraram produtos;SELECT CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONEFROM CUSTOMER LEFT JOIN REQUEST ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMERWHERE REQUEST.CDCUSTOMER IS NULL;--F)O nome e o telefone dos fornecedores que fornecem o produto ‘leite em po”
--ou o produto “agua mineral”;

SELECT SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE
FROM SUPPLIER INNER JOIN PRODUCT 
ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER 
AND PRODUCT.NMPRODUCT = 'leite em po' OR PRODUCT.NMPRODUCT = 'agua mineral';

--G)O nome e o fornecedor do produto que já foi vendido mais que 3 vezes.

SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER
FROM PRODUCT INNER JOIN SUPPLIER
ON PRODUCT.CDSUPPLIER = SUPPLIER.CDSUPPLIER
INNER JOIN PRODUCTREQUEST
ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT
GROUP BY PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER
HAVING COUNT(PRODUCTREQUEST.CDPRODUCT) > 3;