--1)Faça um script:

----A)Excluindo todos os clientes que não compraram nada ainda;

BEGIN TRANSACTION;

DELETE CUSTOMER FROM CUSTOMER LEFT JOIN REQUEST
ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER WHERE REQUEST.CDCUSTOMER IS NULL;

COMMIT;

----B)Excluindo todos os fornecedores que não forneceram nenhum produto;

BEGIN TRANSACTION;

DELETE SUPPLIER FROM SUPPLIER LEFT JOIN PRODUCT
ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER WHERE PRODUCT.CDSUPPLIER IS NULL;

COMMIT;

----C)Atualizando o valor de venda pelo preço original do produto;

BEGIN TRANSACTION;

UPDATE PRODUCTREQUEST SET VLUNITARY = PRODUCT.VLPRICE FROM DBO.PRODUCTREQUEST
INNER JOIN PRODUCT ON PRODUCT.CDPRODUCT = PRODUCTREQUEST.CDPRODUCT;

COMMIT;

----D)Acrescentando a tabela do fornecedor o campo dsstatus (10);BEGIN TRANSACTION;ALTER TABLE SUPPLIERADD DSSTATUS VARCHAR(10);COMMIT;----E)Atualizando o status do fornecedor para ‘INATIVO’ nos fornecedores que não
----forneceram nenhum produto.

BEGIN TRANSACTION;

UPDATE SUPPLIER SET DSSTATUS = 'INATIVO' FROM DBO.SUPPLIER
LEFT JOIN PRODUCT
ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER WHERE PRODUCT.CDSUPPLIER IS NULL;

COMMIT;

----F)Faça o script que atualize o campo endereço do cliente para
----‘DESCONHECIDO’ onde o endereço for NULO

BEGIN TRANSACTION;

UPDATE CUSTOMER SET NMADRESS = 'DESCONHECIDO' FROM DBO.CUSTOMER
WHERE CUSTOMER.NMADRESS IS NULL;

COMMIT;

----G)Faça o script que insira todos os produtos em todos os pedidos. Quantidade
----10 e preço original do produto.

BEGIN TRANSACTION;

INSERT INTO PRODUCTREQUEST (CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT PRODUCTREQUEST.CDREQUEST, PRODUCT.CDPRODUCT, 10, PRODUCT.VLPRICE
FROM PRODUCT
CROSS JOIN PRODUCTREQUEST;

COMMIT;

--2)Faça as seguintes consultas:

----A)Todos os produtos comprados por cliente (nome), com o número de vezes que
----foi comprado, a quantidade total comprada e o valor total já pago por aquele
----produto;

SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, COUNT(PRODUCTREQUEST.CDPRODUCT) AS TIMESBOUGHT, SUM(PRODUCTREQUEST.QTAMOUNT) AS AMOUNTBOUGHT, 
SUM(PRODUCTREQUEST.QTAMOUNT * PRODUCTREQUEST.VLUNITARY) AS TOTALPAID
FROM CUSTOMER INNER JOIN REQUEST ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT GROUP BY CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT ORDER BY CUSTOMER.NMCUSTOMER;

----B)O número de pedidos e o total comprado por cliente (nome) no ano de 2003;

SELECT CUSTOMER.NMCUSTOMER, COUNT(REQUEST.CDCUSTOMER) AS REQUESTSMADE, SUM(PRODUCTREQUEST.QTAMOUNT) AS TOTALITEMSBOUGHT
FROM CUSTOMER INNER JOIN REQUEST ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST GROUP BY CUSTOMER.NMCUSTOMER;

----C)O nome do fornecedor, seu telefone, o nome do produto, seu preço e a
----quantidade em estoque, o fornecedor deve aparecer mesmo que não tenha
----nenhum produto;

SELECT SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE, PRODUCT.NMPRODUCT, PRODUCT.VLPRICE, PRODUCT.QTSTOCK
FROM SUPPLIER LEFT JOIN PRODUCT ON SUPPLIER.CDSUPPLIER = PRODUCT.CDSUPPLIER;

----D)O nome do cliente, a data do pedido e o valor total, o cliente deve aparecer
----mesmo que não tenha feito nenhum pedido.

SELECT CUSTOMER.NMCUSTOMER, REQUEST.DTREQUEST, REQUEST.VLTOTAL
FROM CUSTOMER LEFT JOIN REQUEST ON CUSTOMER.CDCUSTOMER = REQUEST.CDCUSTOMER;
