CREATE DATABASE dbLista1;

USE dbLista1;

--A)Faça os scripts para a criação das tabelas, sem as constraints;
CREATE TABLE PRODUCTREQUEST (
    CDREQUEST INTEGER NOT NULL,
	CDPRODUCT INTEGER NOT NULL,
	QTAMOUNT INTEGER NOT NULL,
	VLUNITARY FLOAT NOT NULL
);

CREATE TABLE REQUEST (
	CDREQUEST INTEGER  NOT NULL IDENTITY,
	DTREQUEST DATE NOT NULL,
	CDCUSTOMER INTEGER NOT NULL,
	DTDELIVER DATE NOT NULL,
	VLTOTAL FLOAT NOT NULL
);

CREATE TABLE PRODUCT (
	CDPRODUCT INTEGER NOT NULL IDENTITY,
	NMPRODUCT VARCHAR(255) NOT NULL,
	CDSUPPLIER INTEGER NOT NULL,
	VLPRICE FLOAT NOT NULL,
	QTSTOCK INTEGER NOT NULL
);

CREATE TABLE CUSTOMER (
	CDCUSTOMER INTEGER NOT NULL IDENTITY,
	NMCUSTOMER VARCHAR(255) NOT NULL,
	NRFONE VARCHAR(255) NOT NULL,
	DSADRESS VARCHAR(255) NOT NULL
);

CREATE TABLE SUPPLIER (
	CDSUPPLIER INTEGER NOT NULL IDENTITY,
	NMSUPPLIER VARCHAR(255) NOT NULL,
	NRFONE VARCHAR(255) NOT NULL
);

--B)Faça os scripts para a criação das chaves primárias das tabelas criadas;

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (CDCUSTOMER);

ALTER TABLE SUPPLIER
ADD PRIMARY KEY (CDSUPPLIER);

ALTER TABLE REQUEST
ADD PRIMARY KEY (CDREQUEST);

ALTER TABLE PRODUCT
ADD PRIMARY KEY (CDPRODUCT);

ALTER TABLE PRODUCTREQUEST
ADD CONSTRAINT CDPRODUCTREQUEST PRIMARY KEY (CDREQUEST,CDPRODUCT);

--C)Faça os scripts para a criação das chaves secundárias das tabelas criadas;

ALTER TABLE REQUEST
ADD FOREIGN KEY (CDCUSTOMER) REFERENCES CUSTOMER(CDCUSTOMER);

ALTER TABLE PRODUCT
ADD FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER(CDSUPPLIER);

ALTER TABLE PRODUCTREQUEST
ADD FOREIGN KEY (CDREQUEST) REFERENCES REQUEST(CDREQUEST);

ALTER TABLE PRODUCTREQUEST
ADD FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT(CDPRODUCT);

--D)Crie um índice para a chave estrangeira da tabela de produtos;

CREATE INDEX PRODUCTINDEX
ON PRODUCT (CDSUPPLIER);

--E)Crie um índice para a chave estrangeira da tabela de pedidos;

CREATE INDEX REQUESTINDEX
ON REQUEST (CDCUSTOMER);

--F)Adicione o campo endereço na tabela de fornecedores;

ALTER TABLE SUPPLIER
ADD DSADRESS VARCHAR(255);

--G)Faça a inserção de um novo cliente com os seguintes dados: Nome = Fabiano,
--Telefone = 99879375 e Endereço = Rua Tijucas, 110, Centro, Joinville – S.C;

INSERT INTO CUSTOMER (NMCUSTOMER,NRFONE,DSADRESS) VALUES ('Fabiano', '99879375', 'Rua Tijucas, 110, Centro, Joinville – S.C');

--H)Faça a inserção de um novo pedido com os seguintes dados: Data do Pedido = 31/01/2008, 
--Cliente = Fabiano (exercício i), Data de Entrega = 05/02/2008 e Total = 54,00;

INSERT INTO REQUEST (DTREQUEST, CDCUSTOMER, DTDELIVER, VLTOTAL) VALUES ('2008-01-31', 1, '2008-02-05', 54);


--I)Atualize o telefone do cliente Fabiano (exercício i) para 99012567

UPDATE CUSTOMER SET NRFONE = '99012567';

--J)Apague as inserções feitas nos exercícios i e j;

DELETE FROM REQUEST WHERE CDREQUEST = 1;

DELETE FROM CUSTOMER WHERE CDCUSTOMER = 1;

--K)Faça o script para excluir todas as tabelas criadas no exercício a.

DROP TABLE PRODUCTREQUEST;
DROP TABLE REQUEST;
DROP TABLE PRODUCT;
DROP TABLE CUSTOMER;
DROP TABLE SUPPLIER;